version: 1
disable_existing_loggers: True

formatters:
  brief:
    format: '%(levelname)-8s | %(name)-35s | %(message)s'
    datefmt: "%I:%M:%S"

  standard:
    format: '%(asctime)s | %(levelname)-8s | %(name)-35s | %(funcName)-20s |%(lineno)4d: %(message)s'
    datefmt: "%I:%M:%S"

  multi_process:
    class: 'logging.Formatter'
    format: '%(asctime)s | %(levelname)-8s | [%(thread |)s] | %(name)-35s | %(funcName)-20s | %(lineno)-4d: %(message)s'

  multi_thread:
    class: 'logging.Formatter'
    format: '%(asctime)s | %(levelname)-8s | [%(process)d] | %(name)-35s | %(funcName)-20s | %(lineno)-4d: %(message)s'

  verbose:
    class: 'logging.Formatter'
    format: '%(asctime)s | %(levelname)-8s | [%(process)d - %(thread)s] | %(name)-35s | %(funcName)-20s | %(lineno)4d: %(message)s'

  multi_line:
    class: 'logging.Formatter'
    format: 'Level: %(levelname)s\nTime: %(asctime)s\nProcess: %(process)d\nThread: %(thread)s\nLogger: %(name)s\nPath: %(module)s:%(lineno)d\nFunction :%(funcName)s\nMessage: %(message)s\n'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: verbose
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: verbose
    filename: info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: verbose
    filename: errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  warning_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: verbose
    filename: warning.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  critical_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: CRITICAL
    formatter: verbose
    filename: critical.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  error_log:
    level: ERROR
    handlers:
      - error_file_handler
    propagate: False

  debug_log:
    level: DEBUG
    handlers:
      - debug_file_handler
    propagate: False

  info_log:
    level: INFO
    handlers:
      - info_file_handler
    propagate: False

  warn_log:
    level: WARNING
    handlers:
      - warning_file_handler
    propagate: False

  critical_log:
    level: CRITICAL
    handlers:
      - critical_file_handler
    propagate: False

root:
  level: DEBUG
  handlers:
    - console
    - debug_file_handler
    - info_file_handler
    - error_file_handler
    - warning_file_handler
    - critical_file_handler
